### ISSUE TITLE
Error after installing extension is Automatic1111 1.7

### ISSUE THREAD

**Issue by Miczu** [groinge/sd-webui-untitledmerger#1]
*** Error loading script: untitled_ui.py
    Traceback (most recent call last):
      File "M:\ML\1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\ML\1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\ML\1111\stable-diffusion-webui\extensions\sd-webui-untitledmerger\scripts\untitled_ui.py", line 7, in <module>
        from scripts.untitled import merger,misc_util
      File "M:\ML\1111\stable-diffusion-webui\extensions\sd-webui-untitledmerger\scripts\untitled\merger.py", line 6, in <module>
        import scripts.untitled.operators as oper
      File "M:\ML\1111\stable-diffusion-webui\extensions\sd-webui-untitledmerger\scripts\untitled\operators.py", line 1, in <module>
        import torch,scipy,cachetools
    ModuleNotFoundError: No module named 'cachetools'

---

**Comment by groinge** [comment]
Fixed in 06b034d
